server:
  port: 8083
spring:
  cloud:
    openfeign:
      okhttp:
        enabled: true
ym:
  db:
    database: ym-user
  redis:
    database: 4
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 300m

